### PR TITLE
Fixes for middleware when reloadOnSearch

### PR DESCRIPTION
**Pull request by neilff**
added fixes for middleware when reloadOnSearch = false, and removed autobind actions

### CODE REVIEW

**Comment by neilff** [comment]
@e-schultz When you have a sec, can you take a look at these proposed changes?

**Comment by e-schultz** [comment]
@neilff if someone modifies the query string directly in the browser, or copy/pastes a link - does the state get updated?

Just wondering if we should also be hooking into [$locationChangeSuccess](https://docs.angularjs.org/api/ng/service/$location#$locationChangeSuccess)

**Comment by neilff** [comment]
@e-schultz Ah, it doesn't... let me play with $locationChangeSuccess... my only concern is that both `$locationChangeSuccess` & `$stateChangeSuccess` are fired when the change from within ui router

**Comment by neilff** [comment]
@e-schultz pushed up the change using `$locationChangeSuccess`

**Pull request merged**
