### PR TITLE
Added stateChangeFinish action to ensure state changes are set in the…

### LINKED ISSUE #74: $stateChange* events are deprecated in upcoming angular-ui-router 1.0.0
While digging into routing, I realized the upcoming update of angular-ui-router is deprecating $stateChange events: https://github.com/angular-ui/ui-router/issues/2219

Instead, the following is recommended:

```
$transitions.onStart({}, function() {});
$transitions.onSuccess({}, function() {});
```

However a solution is proposed [here](https://github.com/angular-ui/ui-router/issues/2655) but I was wondering if there should be any adjustment to redux-ui-router as a consequence?

### PR DESCRIPTION
**Pull request by hally9k**
… app state before components are instantiated.

@Nighthawk14 Do you want to have a look at this for me... I had very minimal time so would be cool to get some verification.

Should fix #74 & #76

### CODE REVIEW

**Comment by Nighthawk14** [comment]
Looks good @hally9k. Nice one! 👍 .
I have tested it on my app and it's seems to behave perfectly.

**Comment by hally9k** [comment]
Thats a really good point actually. Master is currently the version that we will publish as 0.7.0 when ui-router goes 1.0. But I take your point. Maybe master should represent our current stable release? I should start a release-0.7.0 branch and reset master to the previous release version. Then once ui-router 1.0s we can release 0.7.0 and merge into master. Does that sound like the right approach to you @Nighthawk14?

**Comment by xlozinguez** [comment]
@hally9k did you guys deploy this on npm? I can't seem to fetch it...
```
npm ERR! No compatible version found: redux-ui-router@^0.7.0
npm ERR! Valid install targets:
npm ERR! 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.4, 0.4.3, 0.4.2, 0.4.0, 0.3.3, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.4, 0.1.3
```

**Comment by xlozinguez** [comment]
I guess I need to use https://www.npmjs.com/package/hally9k-redux-ui-router instead of https://www.npmjs.com/package/redux-ui-router @hally9k ?

**Comment by Nighthawk14** [comment]
@xlozinguez Not yet, that will be done as part of the merging of #80. That will probably be not `0.7.0` but `0.7.0-beta.1` anyway :).

**Comment by hally9k** [comment]
I will get try and deploy the beta version shortly. Sorry for the hold up!

**Comment by jesperzach** [comment]
@hally9k any updates? :)

**Pull request closed without merging**
